eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: DriverService
          uri: http://localhost:9099
          predicates:
            - Path=/driver/**
        - id: UserService
          uri: http://localhost:9098
          predicates:
            - Path=/user/**

        - id: ManagerService
          uri: http://localhost:9100
          predicates:
            - Path=/manager/**

        - id: BookingService
          uri: http://localhost:9101
          predicates:
            - Path=/booking/**
